### ISSUE TITLE
можно ли повысить скорость работы?

### ISSUE THREAD

**Issue by SergiiMytakii** [fk-war-in-ukraine/report-telegram-channels#10]
Сейчас 1 репорт в 2-3 минуты,  а учитывая ,  что  dirty channels  много,  то эффективность слабая.  Пока все каналы из списка продолжают жить
И второе,  хотел бы уточнить,  система защиты в Телеграм не блочит наши усилия?

**Comment by fk-war-in-ukraine** [comment]
@SergiiMytakii к сожалению, да, антифлуд телеги может блочить усилия, поэтому и приходится делать большие задержки между запросами. Тут только один выход - подключать больше людей.
