### ISSUE TITLE
Ни с того ни с сего повалили ошибки.

### ISSUE THREAD

**Issue by kt368** [fk-war-in-ukraine/report-telegram-channels#11]
Проработал пол списка, дальше всё идёт с результатом Failed.
![image](https://user-images.githubusercontent.com/7873883/156835129-cdf1b1de-bdc1-43f4-910f-b0bba6905739.png)
Сильно обрезал dirty_channels.txt.
Всё равно ошибки валятся.

**Comment by fk-war-in-ukraine** [comment]
@kt368 стяни свежий мастер и запусти еще раз, там должна отображаться причина ошибки.

Скорее всего, включается антифлуд телеги, с этим ничего не сделаешь. :( Только делить список на 2 части и работать с разных акков, как вариант.

**Comment by kt368** [comment]
О, да, скрипт сильно изменился, много функционала добавилось.
Пробую.
