### ISSUE TITLE
почему задержка на новом акк

### ISSUE THREAD

**Issue by SergiiMytakii** [fk-war-in-ukraine/report-telegram-channels#12]
Не могу понять:  взял 3-й акк телеграмма (только зарегистрировал) 
запускаю: и сразу предлагает ждать 50тыс секунд

**Comment by SergiiMytakii** [comment]
блин,  и проверяю,  каналы за исключением парочки - все работают

**Comment by Eugeneshemchuk** [comment]
Телеграм міг тегнути аномальну активність. Я коли лишаю на ніч то під ранок з свого IP більше не можу працювати. Навіть з іншими app id і hash. Мені здається треба з різних IP пробувати запускати.

**Comment by SergiiMytakii** [comment]
меняю страну в впн,  ip   же меняется,  но как то все равно это не помогает

**Comment by fk-war-in-ukraine** [comment]
Скорее всего, как-то работает антифлуд:( Сейчас решения нет.
