### ISSUE TITLE
Не слишком ли часто репорты идут? Слушал что телеграм за такое банил

### ISSUE THREAD

**Issue by kt368** [fk-war-in-ukraine/report-telegram-channels#5]
Сейчас в скрипте 0.3 секунды, может стоить увеличить хотя бы до 10 секунд?

**Comment by ahndmal** [comment]
@kt368 согласно FAQ документации (https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this) лучше не превышать:

- для чатов - не больше 1 сообщения в секунду
- системные нотификации (ка я понимаю, это как раз то, что здесь) - не больше 30 запросов в секунду 
- нотификации на группы - ~30 пользователей в секунду

Исходя из этого, ~3 запроса в секунду должно быть ОК. Хотя, конечно, могут быть еще нюансы.

**Comment by fk-war-in-ukraine** [comment]
Заменил 0.3 sec → 0.5 sec, должно быть ок, спасибо. Пока закрываю issue.
