### ISSUE TITLE
Report from different accounts

### ISSUE THREAD

**Issue by katakanak** [fk-war-in-ukraine/report-telegram-channels#7]
Привіт, не підкажете таку річ. Де зберігається твій логін (тому що ж при повторному запуску вже не запитує логін) або як запустити під іншим аккаунтом?

**Comment by fk-war-in-ukraine** [comment]
@JuliaSavchuk привіт, логін зберігається у файліку `ReportDirtyChannels.sessions` в каталозі проєкту. Якщо треба запустити під іншим акаунтом, то:
1) видали цей файл;
2) запусти скрипт еще раз з іншим `api_id` / `api_hash`.
