### ISSUE TITLE
ошибка   SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by SergiiMytakii** [fk-war-in-ukraine/report-telegram-channels#8]
python3 main.py 12345678 73e8b876a7e845f3acd0afb54e666666
                                                   ^
SyntaxError: invalid decimal literal

не нравится что то в  api_hash

**Comment by fk-war-in-ukraine** [comment]
@SergiiMytakii скинь, плз, полный текст ошибки, на какую строку ругается.

**Comment by SergiiMytakii** [comment]
![Screenshot 2022-03-03 104346](https://user-images.githubusercontent.com/62716960/156528950-70deb2a6-d02b-48fd-9ee5-c5fdc6150e09.png)

**Comment by fk-war-in-ukraine** [comment]
@SergiiMytakii

А попробуй в кавычки взять.

```python3 main.py "1255XX" "73e8..."```

**Comment by SergiiMytakii** [comment]
> 

SyntaxError: invalid syntax

**Comment by fk-war-in-ukraine** [comment]
@SergiiMytakii а ты запускаешь просто из командной строки или из командной строки Python? По-моему, второе, а надо первое.

**Comment by SergiiMytakii** [comment]
да,  точно,  спасибо

**Comment by SergiiMytakii** [comment]
![image](https://user-images.githubusercontent.com/62716960/156570584-e3e60905-d07a-4bf4-b9cf-cb9d6f125c6d.png)
процесс пошел,  спасибо,  парни!

**Comment by fk-war-in-ukraine** [comment]
@SergiiMytakii Слава Україні!
