### ISSUE TITLE
New channels

### ISSUE THREAD

**Issue by nikshev** [fk-war-in-ukraine/report-telegram-channels#9]
https://t.me/warjournaltg
https://t.me/boris_rozhin
https://t.me/grey_zone
https://t.me/go338
https://t.me/omonmoscow
https://t.me/wingsofwar
https://t.me/chvkmedia
https://t.me/hackberegini
https://t.me/mig41
https://t.me/pezdicide
https://t.me/SergeyKolyasnikov
https://t.me/MedvedevVesti
https://t.me/SIL0VIKI
https://t.me/balkanossiper
https://t.me/pl_syrenka
https://t.me/brussinf
https://t.me/lady_north
https://t.me/sex_drugs_kahlo
https://t.me/usaperiodical
https://t.me/russ_orientalist
https://t.me/vladlentatarsky @neoficialniybezsonov
https://t.me/rybar
https://t.me/milinfolive
https://t.me/vsu_info_bot 
https://t.me/sputnikipogrom
https://t.me/czartv
https://t.me/iskra_press
https://t.me/podled
https://t.me/Govorit_Topaz
https://t.me/chernaya100
https://t.me/wargonzo
https://t.me/swodki
https://t.me/lacewars
https://t.me/golosrn
https://t.me/listva_books_msk
https://t.me/listva_books
https://t.me/randomrussianchannel
https://t.me/russkiememy
https://t.me/Andrafanaslive
https://t.me/extra_vaganza
https://t.me/pamyat_society
https://t.me/vladlentatarskiy 
https://t.me/rightcourse
https://t.me/holmogortalks
https://t.me/SonOfMonarchy
https://t.me/riakatysha
https://t.me/juchkovsky
https://t.me/kostisovesti
https://t.me/nikral
https://t.me/illegalthoughts
https://t.me/rus_jansen
https://t.me/chernaya100kitchen
https://t.me/adirect
https://t.me/teleskopby
https://t.me/blondiefor
https://t.me/BeregTime
https://t.me/ZnakiZelenaTara
https://t.me/echoofthestruggle
https://t.me/russkievperedi
https://t.me/vexiistorii
https://t.me/nikitaizyumov2020
https://t.me/zola_of_renovation
https://t.me/rqnst
https://t.me/russkie02
https://t.me/pravcheloveka
https://t.me/Ags_Donbass
https://t.me/arbaletgovorit
https://t.me/neoficialniybezsonov
https://t.me/nashiivashi
https://t.me/Za_Derjavy
https://t.me/Ukrainian_format
https://t.me/ruscos
https://t.me/dvinskyclub
https://t.me/WarDonbass
https://t.me/CenterCIGR
https://t.me/natsmeme
https://t.me/redpilled_based
https://t.me/kitezhgradec
http://t.me/r_slovo
https://t.me/rus_demiurge
https://t.me/vesparevenge
https://t.me/rhos_marsoff
http://t.me/Russian_Reconquista
https://t.me/patriotkbr
https://t.me/vandalslavyansk
https://t.me/pogromach
https://t.me/o4evidez37
https://t.me/novorosinform
https://t.me/dobr_rus
https://t.me/great_and_sovereign
https://t.me/podchinputina
https://t.me/stb_safety
https://t.me/asgardiriyskiy
https://t.me/topkbr
https://t.me/WarofNewRussia
https://t.me/orhoresistanse
https://t.me/VertChinChon
https://t.me/IanusCCCLXV 
https://t.me/civsoc_traditional
https://t.me/Tretii_Rim
http://t.me/layjka
https://t.me/thehandofthekremlin
https://t.me/NewsOfYakutia
https://t.me/nvreport
https://t.me/fn2020ru
https://t.me/karga4
https://t.me/siberia_right_centr
https://t.me/NPK_tv
https://t.me/ChetyrePera
https://t.me/vendeemag
https://t.me/majorselivanov
https://t.me/snr_info
https://t.me/tavri
https://t.me/russoeschatology
https://t.me/unitynationnarmy/
https://t.me/unitynationnarmyspb
https://t.me/PeremogaVSUbot
https://t.me/+9GPKhDPGHPAzZjdi
https://discord.gg/G8YYbhYTnr
https://discord.gg/gBJTsRRRmW
https://t.me/KillRussianSites
https://t.me/regular_patty
https://t.me/proxy_list_misha
https://t.me/studentcyberarmy
https://t.me/+97Y45he5lOI2ZTky
https://t.me/+nqYNNt0qoKU4MTRi
https://t.me/screwynet
https://t.me/+deK4nOA9Z-s4YTcy
https://t.me/ddosRussians
https://t.me/mediapartisans
https://t.me/smallpharm
https://t.me/sorok40russia
https://t.me/vsrfsupport
https://t.me/strelkovii
https://t.me/beatbarenboim
https://t.me/Doninside
https://t.me/ASupersharij
https://t.me/krasovkin
https://t.me/Ratnik2nd
https://t.me/warfakes
https://t.me/+bmi0SKMtLwpiODcy
https://t.me/rlz_the_kraken
https://t.me/bbbreaking
https://t.me/Ugolok_Sitha
https://t.me/+BWHcXHBu8mY4YzRi
https://t.me/informator_life
https://t.me/chesnokmedia
https://t.me/ghost_of_novorossia
https://t.me/notes_veterans
https://t.me/diplomatia
https://t.me/bulbe_de_trones
https://t.me/olegtsarov
https://t.me/akimapache
https://t.me/Hard_Blog_Line
https://t.me/ice_inii
https://t.me/infantmilitario
https://t.me/rt_russian
https://t.me/gazetaru
https://t.me/rbc_news
https://t.me/vedomosti
https://t.me/tass_agency
https://t.me/kremlinprachka
https://t.me/RVvoenkor 
https://t.me/rusvesnasu 
https://t.me/oldminerkomi
https://t.me/julia_chicherina
https://t.me/nezhurka
https://t.me/Sladkov_plus
https://t.me/news_forfree
https://t.me/mikayelbad
https://t.me/donbassr
https://t.me/voenkorKotenok
https://t.me/marochkolive
https://t.me/miroshnik_r
https://t.me/sev_polit_takt
https://t.me/cmiye
https://t.me/JokerDNR
https://t.me/svarschiki
https://t.me/donbass_segodnya
https://t.me/epoddubny
https://t.me/RtrDonetsk
https://t.me/medvedev_note
https://t.me/RVvoenkor
https://t.me/conqueror95
https://t.me/rusyerevantoday
https://t.me/vysokygovorit
https://t.me/ontnews
https://t.me/delyagin
https://t.me/military_corner
https://t.me/intelslava
https://t.me/vorposte
https://t.me/RIA82rf
https://t.me/MaterikMedia
https://t.me/intuition2036
https://t.me/karaulny
https://t.me/glavpolit
https://t.me/parbut
https://t.me/mardanaka
https://t.me/tikandelaki
https://t.me/kbrvdvkr
https://t.me/skfo_telegraph
https://t.me/ia_steklomoy
https://t.me/BorodaV
https://t.me/akitilop
https://t.me/gossluga
https://t.me/glavmedia
https://t.me/operdrain
https://t.me/minzdravny
https://t.me/MayorFSB
https://t.me/orfosvinstvo
https://t.me/Baronova
https://t.me/pridybaylo
https://t.me/ChasovojPogody
https://t.me/robabayan
https://t.me/skabeeva
https://t.me/nailyaaskerzade
https://t.me/prbezposhady
https://t.me/vladivostok1978
https://t.me/vrogov
https://t.me/dplatonova
https://t.me/SolovievLive
https://t.me/sashakots
https://t.me/evgenyprimakov
https://t.me/akashevarova
https://t.me/superdolgov
https://t.me/romagolovanov
https://t.me/ASGasparyan
https://t.me/annashafran
https://t.me/ntnzn
https://t.me/NeSocSeti
https://t.me/radlekukh
https://t.me/egorgalenko
https://t.me/yudenich
https://t.me/MaximYusin
https://t.me/+bmi0SKMtLwpiODcy 
https://t.me/rbc_news 
https://t.me/gazetaru 
https://t.me/vedomosti 
https://t.me/tass_agency 
https://t.me/ukr_novosti_voina 
https://t.me/legitimniy 
https://t.me/rezident_ua 
https://t.me/first_political 
https://t.me/nabludatels 
https://t.me/Ten_NaPleten 
https://t.me/sheptoon 
https://t.me/KrokooDil 
https://t.me/spletnicca 
https://t.me/Ze_kartel 
https://t.me/zradaperemoga 
https://t.me/skosoi 
https://t.me/buntariy 
https://t.me/life_odessa 
https://t.me/legitimniy_live 
https://t.me/cherniy_kvartal 
https://t.me/EQUILIBRIUM2019 
https://t.me/chistoprikol 
https://t.me/newswash 
https://t.me/MediaKiller2021 
https://t.me/svodkidpr 
https://t.me/swodki 
https://t.me/pushilindenis 
https://t.me/oddr_info 
https://t.me/luganskallnews 
https://t.me/novorosinform 
https://t.me/ghost_of_novorossia 
https://t.me/antimaidan 
https://t.me/faceofwar 
https://t.me/uranews 
https://t.me/politrings 
https://t.me/chergovii 
https://t.me/boris_rozhin 
https://t.me/hackberegini 
https://t.me/go338 
https://t.me/omonmoscow 
https://t.me/wingsofwar 
https://t.me/pezdicide 
https://t.me/SIL0VIKI 
https://t.me/balkanossiper 
https://t.me/pl_syrenka 
https://t.me/lady_north 
https://t.me/sex_drugs_kahlo 
https://t.me/usaperiodical 
https://t.me/russ_orientalist 
https://t.me/vladlentatarsky 
https://t.me/neoficialniybezsonov 
https://t.me/rybar 
https://t.me/KatiaTxiLive
https://t.me/mordor_world
https://t.me/MariaVladimirovnaZakharova
https://t.me/istorijaoruzija
https://t.me/shot_shot
https://t.me/ukraina_ru
https://t.me/MakarenkoLive
https://t.me/Abbasdjuma
https://t.me/dataleak
https://t.me/+VKWSAJJVAtsyZmE6
https://t.me/ssleg
https://t.me/voenacher
https://t.me/CIS91
https://t.me/vityzeva
https://t.me/+ikY4F6qfDuYyZDNi
https://t.me/Generalnote
https://t.me/vpoanalytics
https://t.me/zvezdanews
https://t.me/vladisdoktor
https://t.me/DailyWar
https://t.me/+s-Mbzo_sP10wYzdi
https://t.me/rostov_na_konu
https://t.me/informational_war_against_russia
https://t.me/kartezianec
https://t.me/wisedruidd
https://t.me/dnronline
https://t.me/dontel 
https://t.me/aleksandr_skif
https://t.me/dnr_live
https://t.me/kondrotenko_art
https://t.me/novostilnr
https://t.me/donetsk_donbass
https://t.me/shortDPR
https://t.me/TELEKANALSTALINGRAD
https://t.me/+cXNiCxswkNY5Y2Ri
https://t.me/bloodysx
https://t.me/ostorozhno_novosti
https://t.me/ok_spn
https://t.me/joinchat/cmqVD-34uLQ0ZWE0
https://t.me/freedom_95_y
https://t.me/wtyhe2375
https://t.me/whytzek
https://t.me/+k5g8O_wC4ZpmNTli
https://t.me/webmland
https://t.me/boomsclaymoreair
https://t.me/putch111
https://t.me/claymoreair
https://t.me/olgerd_semenow
https://t.me/DmitriySteshin
https://t.me/dimsmirnov175
https://t.me/vv_volodin 
https://t.me/boilerroomchannel
https://t.me/deanon_russians_bot
https://t.me/ddos_rugoverment_bot
https://t.me/helps_zsubot
https://t.me/PeremogaVSUbot 
https://t.me/Goyko_mitRich
https://t.me/sashakots 
https://t.me/krispotupchik 
https://t.me/glavmedia 
https://t.me/mediatech 
https://t.me/glavpolit 
https://t.me/rasstrelny 
https://t.me/savanichi 
https://t.me/SolovievLive 
https://t.me/politadequate 
https://t.me/imnotbozhena 
https://t.me/MariaVladimirovnaZakharova 
https://t.me/russica2 
https://t.me/MedvedevVesti 
https://t.me/orda_mordora 
https://t.me/videoduma 
https://t.me/Abbasdjuma 
https://t.me/antiskrepa
https://t.me/LastOfRus
https://t.me/polittemnik
https://t.me/media_soldier 
https://t.me/redacted6 
https://t.me/madam_secretar 
https://t.me/mayday_7700
https://t.me/PolitTransit
https://t.me/vibornyk
https://t.me/krimski
https://t.me/volodin_saratov
https://t.me/russicabrief
https://t.me/huliwar
https://t.me/nightstrikers
https://t.me/TanyaButskaya
https://t.me/nastol
https://t.me/HouseOfCardsRussia
https://t.me/riafan_everywhere
https://t.me/sergeymiheev
https://t.me/internetsmi
https://t.me/izolentalive
https://t.me/na_urale
https://t.me/ukr_leaks
https://t.me/kaktovottak
https://t.me/SwissVatnik
https://t.me/fahrenheit1724
https://t.me/alexandr_malkevich
https://t.me/rasstriga
https://t.me/zamesinfo
https://t.me/mislinemisli
https://t.me/krasniydom
https://t.me/anti_navalny
https://t.me/vechernii_m
https://t.me/spravedlivo
https://t.me/remeslaw
https://t.me/lesyaryabtseva
https://t.me/MuesliLavrova
https://t.me/imerkouri
https://t.me/mediakiller
https://t.me/polkovnikt
https://t.me/archivarius_dz
https://t.me/margaritasimonyan
https://t.me/big_brother_oren
https://t.me/fuckyouthatswhy
https://t.me/NovostiDamask
https://t.me/fcpeshka
https://t.me/streli_kazbeka
https://t.me/volrota
https://t.me/Wek_ru
https://t.me/PolitBulka
https://t.me/astramilitarum
https://t.me/Buddykiton
https://t.me/riafan
https://t.me/dr_alex_sosnowski
https://t.me/niemandswasser
https://t.me/The_Idiot
https://t.me/politakula
https://t.me/vprorok
https://t.me/savchuk_serg
https://t.me/radiogram_ru
https://t.me/krassdogs
https://t.me/EvPanina
https://t.me/pvsgns
https://t.me/radio_sputnik
https://t.me/knightsmove
https://t.me/Nevrotique
https://t.me/OkoloBaikala
https://t.me/Prigovorchiki
https://t.me/mediakinesis
https://t.me/NikonovLive
https://t.me/ekvinokurova
https://t.me/zubovskiy4
https://t.me/godeye_ru
https://t.me/insect_life
https://t.me/breakingmash
https://t.me/politanimalss
https://t.me/lesonaval
https://t.me/oleglurie
https://t.me/sueverdem
https://t.me/nomenclatura
https://t.me/chanelpeskova
https://t.me/oko_ok
https://t.me/rabotaembrat
https://t.me/politrussiacom
https://t.me/Ivorytowers
https://t.me/good78news
https://t.me/analyst_on_the_couch
https://t.me/economika
https://t.me/postposttruth
https://t.me/kashinguru
https://t.me/nealbin
https://t.me/voenzhur
https://t.me/mediasrachi3
https://t.me/prosmis
https://t.me/sevkav
https://t.me/new_militarycolumnist
https://t.me/navideovidno
https://t.me/munpes
https://t.me/kononenkome
https://t.me/teory_elit
https://t.me/aviadispet4er
https://t.me/windowsonaurora
https://t.me/post_enot
https://t.me/rianovosti
https://t.me/docpro
https://t.me/spbformat
https://t.me/russianfuture
https://t.me/zakuliska
https://t.me/zradaperemoga
https://t.me/topgun_spb
https://t.me/mysly
https://t.me/RegnumMoscow
https://t.me/migdalsergei
https://t.me/RU_S_INT
https://t.me/apostolaki_the_cat
https://t.me/Ms_krasota
https://t.me/fakecontrol
https://t.me/daviegoblyad
https://t.me/duma_2021
https://t.me/tvjihad
https://t.me/act_next
https://t.me/pdmnews
https://t.me/RIAKremlinpool
https://t.me/varlamov_news
https://t.me/kremlin_bashnya
https://t.me/topspb_tv
https://t.me/pltrk
https://t.me/degrag
https://t.me/gogoKremlin
https://t.me/sinelor
https://t.me/crimeainform
https://t.me/TJournal
https://t.me/stormdaily
https://t.me/Federalcity
https://t.me/fake_news_ru
https://t.me/ENews112
https://t.me/dvachannel
https://t.me/liubotyn
https://t.me/stuksnizu
https://t.me/nourlnews
https://t.me/kpotupchik
https://t.me/sovietleningrad
https://t.me/agitpolk
https://t.me/chp_show
https://t.me/karocheeto
https://t.me/SuperRu
https://t.me/vorchunmedia
https://t.me/tsargradtv
https://t.me/rian_ru
https://t.me/online47news
https://t.me/bydrbre
https://t.me/ruredmantis
https://t.me/vmarahovsky
https://t.me/ShlyapaChelentano
https://t.me/NN_strelka
https://t.me/martyoshka
https://t.me/n0comments
https://t.me/dorogoydedushka
https://t.me/nicstavrogin
https://t.me/icokaraulny
https://t.me/ne_propaganda
https://t.me/abunin
https://t.me/vybora
https://t.me/Zloyrusskiy_bot
https://t.me/vsu_info_bot
https://t.me/telemanagerua 
https://t.me/p_golov 
https://t.me/Tima_KRKDL 
https://t.me/smmreklam7 
https://t.me/A_manager2
https://t.me/Pricool_bot 
https://t.me/washadminbot 
https://t.me/ted_manager 
https://t.me/Manager_LuganskAllNews
https://t.me/Vladimir12144  
https://t.me/cherhoviionline
https://t.me/dnepr_partizani
https://t.me/nm_dnr
https://t.me/parbut 
https://t.me/genshab 
https://t.me/dimsmirnov175 
https://t.me/vatfor 
https://t.me/georgy_ma
https://t.me/military_production
https://t.me/zapashnyru
https://t.me/egorovznaet
https://t.me/KharkovWarZ
https://t.me/vv_volodin
https://t.me/vagner_group
https://t.me/supermetavers
https://t.me/gettafuckout

**Comment by fk-war-in-ukraine** [comment]
Спасибо!

Добавь, плз, сюда через PR: https://github.com/fk-war-in-ukraine/report-telegram-channels/blob/master/dirty_channels.txt

**Comment by vaselo** [comment]
Хочу порадити трюк для уникнення дублів:
Notepad++ дозволяє легко позбавитися дублів:

Edit->Line Operations->Sort Lines Lex. Ascending Ignoring Case 
Edit->Line Operations->Remove Consecutive Duplicate Lines


Так додані/видалені урли буде добре видно в git diff, а також позбавимося дублів

**Comment by vaselo** [comment]
Відкрив PR, додав власних посилань зібраних з https://t.me/stoprussiachannel
і включив всі посилання з цього issue.

Див #13

**Comment by fk-war-in-ukraine** [comment]
Спасибо, смержил.
